version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew createDB -PdbName=fineract_tenants

      - run: ./gradlew createDB -PdbName=fineract_default

      - run: TZ=Asia/Kolkata ./gradlew clean test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build
